name = "glif-node"
type = "webpack"
route = 'dev.glif.link/*'
zone_id = '28db60a97266a8163a498a6d20046a9e'
usage_model = ''
compatibility_flags = []
workers_dev = true
site = {bucket = "./out",entry-point = "workers-site"}
compatibility_date = "2023-10-02"

[env.calibration]
name = "node-calibration"
vars = { ENVIRONMENT = "calibration" }
route = 'node-calibration.glif.link/*'

[env.mainnet]
name = "node-mainnet"
vars = { ENVIRONMENT = "production" }
route = 'node.glif.link/*'
